[package]
name = "jerry"
version = "0.1.0"
edition = "2021"

[dependencies]
enigo = "0.1.3"
screenshots = "0.8.6"
#tts = "0.25.6"
rand = "0.8.4"
tokio = { version = "1.35.1", features = ["full"] }
serde = { version = "1.0.195", features = ["derive"] }
toml = "0.8.8"
lazy_static = "1.4.0"