[package]
name = "jerry"
version = "0.1.0"
edition = "2021"

[dependencies]
enigo = "0.1.3"
screenshots = "0.8.6"
#display-info = "0.4.8"
# we're using enigo for this until we need to implement multi-display
tts = "0.25.6"
rand = "0.8.4"