name: cargo-clippy
run-name: cargo clippy
on: [push]
jobs:
  clippy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: stable
      - run: cargo clippy --features advanced,invisibility