name: cargo-clippy
run-name: cargo clippy
on: [push]
jobs:
  clippy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: stable
      - name: clippy
        run: cargo clippy
      - name: clippy adv
        run: cargo clippy --features advanced
      - name: clippy inv
        run: cargo clippy --features invisibility
      - name: clippy adv,inv
        run: cargo clippy --features advanced,invisibility